apiVersion: v1
kind: PersistentVolume
metadata:
  name: nvme-pv
spec:
          capacity:
                 storage: 400Gi
          persistentVolumeReclaimPolicy: Delete
          accessModes:
            - ReadWriteOnce
          storageClassName: local-storage
          local:
              path: /dev/nvme1n1
          nodeAffinity:
            required:
             nodeSelectorTerms:
                  - matchExpressions:
                      - key: "disktype"
                        operator: In
                        values:
                          - "nvme-ssd"

